#!/bin/bash
# Script Generated by DeepSeek V4 Pro

TERMUX_PKG_HOMEPAGE=https://github.com/jaqchen/sysutil
TERMUX_PKG_DESCRIPTION="Lua 5.4 module providing system utilities"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="Ye Jiaqiang <yejq.jiaqiang@gmail.com>"
TERMUX_PKG_VERSION=1.0.1
TERMUX_PKG_SRCURL=file:///home/yejq/program/sysutil
TERMUX_PKG_SHA256=SKIP_CHECKSUM
TERMUX_PKG_API_LEVEL=28
TERMUX_PKG_DEPENDS="lua54"
TERMUX_PKG_BUILD_DEPENDS="libandroid-glob"
TERMUX_PKG_BUILD_IN_SRC=true

termux_step_make() {
	local _cflags="$CFLAGS $CPPFLAGS -fPIC -O2 -fno-omit-frame-pointer -I$TERMUX_PREFIX/include/lua5.4"
	local objs="sysutil.o apputil.o zsha256_util.o base64.o"

	$CC $_cflags -c sysutil.c    -o sysutil.o
	$CC $_cflags -c apputil.c    -o apputil.o
	$CC $_cflags -c zsha256_util.c -o zsha256_util.o
	$CC $_cflags -c base64.c     -o base64.o

	$CC -shared -o sysutil.so $objs $LDFLAGS
	$STRIP -s sysutil.so
}

termux_step_make_install() {
	install -Dm600 sysutil.so "$TERMUX_PREFIX/lib/lua/5.4/sysutil.so"
}
