#!/bin/bash
# Script Generated by DeepSeek V4 Pro
#
# Build sysutil.so (Lua 5.4 C module) for Termux on AARCH64/Android
#
# Usage:
#   ./build.sh          - Build sysutil.so
#   ./build.sh clean    - Clean build artifacts
#   ./build.sh install  - Build and install to Lua module path
#
# Supports two build modes:
#   1. Native build inside Termux on Android (auto-detected)
#   2. Cross-compilation from Linux x86_64 using Android NDK
#
# For cross-compilation, the Android NDK must be installed.  The script
# automatically downloads Lua 5.4 headers if not found.  Lua C modules
# are loaded by the Lua interpreter at runtime and do NOT need to link
# against liblua at build time.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LUA_VERSION="5.4"
_LUA_VER="54"                       # "5.4" -> "54" for include path

# ─── detect build environment ───────────────────────────────────────

IN_TERMUX=false
if [ -d "/data/data/com.termux/files/usr" ]; then
	IN_TERMUX=true
fi

# ─── helper: find or fetch Lua headers ─────────────────────────────

_find_lua_headers() {
	local cand="$1"
	if [ -f "$cand/lua.h" ] && [ -f "$cand/lauxlib.h" ]; then
		echo "$cand"
		return 0
	fi
	return 1
}

_download_lua_headers() {
	local src_dir="$HOME/lib/lua-${LUA_VERSION}"
	if _find_lua_headers "$src_dir/src" >/dev/null 2>&1; then
		LUA_INCDIR="$src_dir/src"
		return 0
	fi
	echo "==> Downloading Lua ${LUA_VERSION} headers..."
	local url="https://www.lua.org/ftp/lua-${LUA_VERSION}.0.tar.gz"
	# try to find the latest patch release
	local patch
	for patch in 8 7 6 5 4 3 2 1 0; do
		url="https://www.lua.org/ftp/lua-${LUA_VERSION}.${patch}.tar.gz"
		if curl -fsI "$url" >/dev/null 2>&1; then
			break
		fi
	done
	mkdir -p "$src_dir"
	curl -fsSL "$url" | tar -xz -C "$src_dir" --strip-components=1
	if _find_lua_headers "$src_dir/src" >/dev/null 2>&1; then
		LUA_INCDIR="$src_dir/src"
		return 0
	fi
	echo "ERROR: Failed to download Lua ${LUA_VERSION} headers"
	return 1
}

# ─── configure build ────────────────────────────────────────────────

if $IN_TERMUX; then
	# ── native build inside Termux ──────────────────────────────

	PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
	CC="${CC:-clang}"
	STRIP="${STRIP:-llvm-strip}"

	LUA_INCDIR="${LUA_INCDIR:-$PREFIX/include/lua${_LUA_VER}}"
	LUA_LIBDIR="${LUA_LIBDIR:-$PREFIX/lib/lua/${LUA_VERSION}}"

	CFLAGS="-Wall -Wno-unused-result -fPIC -D_GNU_SOURCE -O2 -fno-omit-frame-pointer"
	CFLAGS="$CFLAGS -I. -I$LUA_INCDIR ${EXTRA_CFLAGS}"
	LDFLAGS="-lpthread ${EXTRA_LDFLAGS}"

	echo "==> Building natively in Termux (AARCH64)"

else
	# ── cross-compilation using Android NDK ─────────────────────

	NDK="${NDK:-$HOME/lib/android-ndk-r29}"
	API_LEVEL="${TERMUX_PKG_API_LEVEL:-28}"
	NDK_BIN="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
	HOST_PLAT="${TERMUX_HOST_PLATFORM:-aarch64-linux-android}"

	if [ ! -x "$NDK_BIN/${HOST_PLAT}${API_LEVEL}-clang" ]; then
		# perhaps the toolchain bundles the API level differently
		NDK_CC="$NDK_BIN/${HOST_PLAT}-clang"
		if [ ! -x "$NDK_CC" ]; then
			# try default clang in NDK with explicit target
			NDK_CC="clang"
		fi
	else
		NDK_CC="$NDK_BIN/${HOST_PLAT}${API_LEVEL}-clang"
	fi

	CC="${CC:-$NDK_CC}"
	STRIP="${STRIP:-llvm-strip}"
	if [ -x "$NDK_BIN/llvm-strip" ]; then
		STRIP="$NDK_BIN/llvm-strip"
	fi

	# find Lua headers: env var > termux-packages prefix > download
	LUA_INCDIR="${LUA_INCDIR:-}"
	if [ -z "$LUA_INCDIR" ]; then
		# check termux-packages staged prefix (if lua54 was built)
		_tp_prefix="$HOME/.termux-build/_cache/termux-prefix"
		LUA_INCDIR="$_tp_prefix/include/lua${_LUA_VER}"
		if ! _find_lua_headers "$LUA_INCDIR" >/dev/null 2>&1; then
			# check system prefix
			LUA_INCDIR="/data/data/com.termux/files/usr/include/lua${_LUA_VER}"
		fi
		if ! _find_lua_headers "$LUA_INCDIR" >/dev/null 2>&1; then
			_download_lua_headers || exit 1
		fi
	fi

	LUA_LIBDIR="${LUA_LIBDIR:-/data/data/com.termux/files/usr/lib/lua/${LUA_VERSION}}"

	CFLAGS="-Wall -Wno-unused-result -fPIC -D_GNU_SOURCE -O2 -fno-omit-frame-pointer"
	CFLAGS="$CFLAGS -I. -I$LUA_INCDIR ${EXTRA_CFLAGS}"
	# Bionic has pthread integrated into libc; no -lpthread needed
	LDFLAGS="${EXTRA_LDFLAGS}"

	echo "==> Cross-compiling for ${HOST_PLAT} (API ${API_LEVEL})"
fi

echo "    CC         = $CC"
echo "    STRIP      = $STRIP"
echo "    CFLAGS     = $CFLAGS"
echo "    LDFLAGS    = $LDFLAGS"
echo "    LUA_INCDIR = $LUA_INCDIR"
echo "    LUA_LIBDIR = $LUA_LIBDIR"

# ─── build targets ──────────────────────────────────────────────────

_clean() {
	echo "==> Cleaning..."
	rm -f "$SCRIPT_DIR"/*.o "$SCRIPT_DIR"/sysutil.so "$SCRIPT_DIR"/zsha256
}

_build() {
	echo "==> Compiling objects..."
	$CC -c $CFLAGS -o "$SCRIPT_DIR/sysutil.o"     "$SCRIPT_DIR/sysutil.c"
	$CC -c $CFLAGS -o "$SCRIPT_DIR/apputil.o"     "$SCRIPT_DIR/apputil.c"
	$CC -c $CFLAGS -o "$SCRIPT_DIR/zsha256_util.o" "$SCRIPT_DIR/zsha256_util.c"
	$CC -c $CFLAGS -o "$SCRIPT_DIR/base64.o"      "$SCRIPT_DIR/base64.c"

	echo "==> Linking sysutil.so..."
	$CC -shared -o "$SCRIPT_DIR/sysutil.so" \
		"$SCRIPT_DIR/sysutil.o" \
		"$SCRIPT_DIR/apputil.o" \
		"$SCRIPT_DIR/zsha256_util.o" \
		"$SCRIPT_DIR/base64.o" \
		$LDFLAGS

	if command -v "$STRIP" >/dev/null 2>&1; then
		"$STRIP" -s "$SCRIPT_DIR/sysutil.so"
	else
		strip -s "$SCRIPT_DIR/sysutil.so" 2>/dev/null || true
	fi

	echo "==> Done: $SCRIPT_DIR/sysutil.so"
	file "$SCRIPT_DIR/sysutil.so" 2>/dev/null || true
}

_install() {
	_build
	local dest="${LUA_LIBDIR}/sysutil.so"
	mkdir -p "$LUA_LIBDIR"
	cp "$SCRIPT_DIR/sysutil.so" "$dest"
	echo "==> Installed: $dest"
}

# ─── main ───────────────────────────────────────────────────────────

case "${1:-build}" in
	clean)   _clean ;;
	install) _install ;;
	build)   _build ;;
	*)
		echo "Usage: $0 [build|clean|install]"
		exit 1
		;;
esac
